// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lilvxmncvkoyhkgxlmfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpbHZ4bW5jdmtveWhrZ3hsbWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODcxMzUsImV4cCI6MjA2Mzc2MzEzNX0.Laj10SBdmgFmropx3P8tKqH7oYg0YX5KLp8DoLlw-u4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);